name: cornext_mobile
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+3

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  web_ffi: 0.7.2 
  path: ^1.7.0
  ffi: ^1.1.2
  moor: ^2.0.0
  moor_ffi: ^0.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.8.0
  http: ^0.12.0+4
  # flushbar: ^1.9.1
  flutter_spinkit: "^4.1.0"
  shared_preferences: ^0.5.6+2
  sqflite: ^1.1.7+3
  path_provider: ^1.4.5
  badges: ^1.1.0
  video_player: ^0.10.11
    # carousel_pro: ^0.0.1
  carousel_pro: ^1.0.0
  carousel_slider: ^1.4.0
  intl: ^0.16.0
  # cached_network_image: ^1.1.3
  chewie: ^0.9.8+1
  connectivity: ^0.4.8+6
  photo_view: ^0.9.0
  autocomplete_textfield: ^1.7.3
  flutter_typeahead: ^1.8.0
  uni_links: ^0.2.0
  cached_network_image: ^2.0.0
  flutter_staggered_grid_view: ^0.2.7
  # video_thumbnail: ^0.1.6
  geolocator: ^5.3.0
  # geopoint_location: ^4.0.0
  image_picker: ^0.6.6+1
  video_thumbnail: ^0.2.0
  # location_permissions: ^2.0.4+1
  android_intent: ^0.3.5+1
  permission_handler: ^4.4.0
  # hardware_buttons: ^1.0.0
  google_fonts: ^1.0.0
  device_info: ^0.4.2+4
  # simple_permissions: ^0.1.9
  razorpay_flutter: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.0
  # test: ^1.16.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/FeedNext-Icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
   - assets/images/cornext-logo-1.jpg
   - assets/images/sample3.jpg
   - assets/images/sample4.jpg
   - assets/images/sample5.jpg
   - assets/images/FN_login-screen-1.jpg
   - assets/images/cornext-logo.png
   - assets/images/cornext-logo-2.png
   - assets/json/farminfo.json
   - assets/images/offerBannerExample.jpg
   - assets/json/productlist.json
   - assets/images/feednext.png
   - assets/json/orderconfirmation.json
   - assets/json/ordertracking.json
   - assets/json/categories.json
   - assets/json/subscriptionlist.json
   - assets/images/FeedNext_Text_Logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Roboto_Condensed
      fonts:
        - asset: assets/fonts/Roboto_Condensed/RobotoCondensed-Regular.ttf
    - family: Roboto_Slab
      fonts: 
        - asset: assets/fonts/Roboto_Slab/static/RobotoSlab-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
    - family: Roboto_Mono
      fonts:
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Regular.ttf
    - family: Open_sans
      fonts:
        - asset: assets/fonts/Open_sans/OpenSans-Regular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Regular.ttf
    - family: Raleway_bold
      fonts:
        - asset: assets/fonts/Raleway/Raleway-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
